#==============================================================================
# Using YAML allows multiple profiles to be included in a single config file.
# Example program arguments:
#   --spring.profiles.active=laptop
#==============================================================================

server:
  port: 8761

spring:
  application:
    name: registry-service

info:
  description: Service registry

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: laptop

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.49 # defaults to 0.85. 0.49 prevents self-preservation mode with a single client.
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
spring:
  profiles: desktop-ide

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.49 # defaults to 0.85. 0.49 prevents self-preservation mode with a single client.
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
spring:
  profiles: docker-cluster

server:
  port: ${EUREKA_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  server:
    renewal-percent-threshold: 0.49 # defaults to 0.85. 0.49 prevents self-preservation mode with a single client.
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_PEER_HOST}:${EUREKA_PEER_PORT}/eureka
